services:
  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: grace-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - GRACE_ENV=production
      - LOG_LEVEL=debug
      - PYTHONUNBUFFERED=1
    volumes:
      - grace-data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      grace-redis:
        condition: service_healthy

  frontend:
    build:
      context: ..
      dockerfile: src/ui/Dockerfile
      target: development  # Use development stage for hot-reloading
    container_name: grace-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8000
    volumes:
      - ../src/ui:/app
      - /app/node_modules
    depends_on:
      - backend
    stdin_open: true
    tty: true

  grace-redis:
    image: redis:7-alpine
    container_name: grace-redis
    restart: unless-stopped
    volumes:
      - grace-redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  grace-data:
  grace-redis-data:

networks:
  default:
    driver: bridge
