version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: ..
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=production
        - VITE_API_URL=/api
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=/api
      - VITE_MANGO_V3_BASE_URL=http://mango-v3-service:8080
      - DOCKER=true
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - grace-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Backend service
  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "8000:8000"
    user: root
    command: sh -c "mkdir -p /app/data/conversation_data/contexts && chmod -R 777 /app/data && python -m src.run_server"
    environment:
      - GRACE_ENV=production
      - DEBUG=false
      - LOG_LEVEL=debug
      - JWT_SECRET=${JWT_SECRET:-grace_default_jwt_secret}
      - FERNET_KEY=${FERNET_KEY:-dGhpc19pc19hX3Byb3Blcl8zMl9ieXRlX2Zlcm5ldF9rZXk=}
      - SESSION_EXPIRY=86400
      - JWT_EXPIRES_IN=86400
      - CHROMA_DB_PATH=./data/chromadb
      - PROFILE_DATA_PATH=./data/profiles.json
      - SOLANA_RPC_URL=${SOLANA_RPC_URL:-https://mainnet.helius-rpc.com/?api-key=aa07df83-e1ac-4117-b00d-173e94e4fff7}
      - SOLANA_NETWORK=mainnet-beta
      - GMGN_API_URL=${GMGN_API_URL:-https://gmgn.ai/defi/router/v1/sol/tx/get_swap_route}
      - GMGN_CHART_URL=${GMGN_CHART_URL:-https://www.gmgn.cc/kline}
      - PHANTOM_APP_URL=${PHANTOM_APP_URL:-https://phantom.app}
      - PHANTOM_CALLBACK_PATH=${PHANTOM_CALLBACK_PATH:-/auth/phantom/callback}
      - PHANTOM_DEEP_LINK=${PHANTOM_DEEP_LINK:-https://phantom.app/ul/v1/}
      - PHANTOM_SESSION_PREFIX=${PHANTOM_SESSION_PREFIX:-phantom_session:}
      - PHANTOM_WALLET_PREFIX=${PHANTOM_WALLET_PREFIX:-phantom_wallet:}
      - PHANTOM_ENCRYPTION_PRIVATE_KEY=${PHANTOM_ENCRYPTION_PRIVATE_KEY:-D7i7hHSJvx64bRQv1nD237nf8Z3WH8AoGmAv7ckX16jL}
      - PHANTOM_ENCRYPTION_PUBLIC_KEY=${PHANTOM_ENCRYPTION_PUBLIC_KEY:-421MrWonHu6VxRAAqYJwEPzACTBLGoeurehPMSKhRzZM}
      - PHANTOM_SESSION_TTL=${PHANTOM_SESSION_TTL:-86400}
      - PHANTOM_RATE_LIMIT=${PHANTOM_RATE_LIMIT:-60}
      - SHORT_TERM_MEMORY_SIZE=${SHORT_TERM_MEMORY_SIZE:-10}
      - MEDIUM_TERM_MEMORY_EXPIRY=${MEDIUM_TERM_MEMORY_EXPIRY:-2592000}
      - MEMORY_THRESHOLD=${MEMORY_THRESHOLD:-0.7}
      - OPENAI_API_KEY=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
      - MANGO_V3_BASE_URL=http://mango-v3-service:8080
      - MANGO_V3_PRIVATE_KEY_PATH=/app/keys/mango_private_key.pem  
    volumes:
      - ../src/data:/app/data
      - ../keys:/app/keys
      - ../src/data/chromadb:/app/data/chromadb
    depends_on:
      - redis
    networks:
      - grace-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Redis service
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - grace-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: redis-server --appendonly yes

# Networks
networks:
  grace-network:
    driver: bridge

# Volumes
volumes:
  redis-data:
  mango-v3-data:
