version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: ./src/ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=/api
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - grace-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Backend service
  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GRACE_ENV=production
      - DEBUG=false
      - LOG_LEVEL=debug
      - JWT_SECRET=
      - FERNET_KEY=
      - SESSION_EXPIRY=86400
      - JWT_EXPIRES_IN=86400
      - CHROMA_DB_PATH=./data/chromadb
      - PROFILE_DATA_PATH=./data/profiles.json
      - SOLANA_RPC_URL=
      - SOLANA_NETWORK=mainnet-beta
      - GMGN_API_URL=
      - GMGN_CHART_URL=
      - PHANTOM_APP_URL=
      - PHANTOM_CALLBACK_PATH=
      - PHANTOM_DEEP_LINK=
      - PHANTOM_SESSION_PREFIX=
      - PHANTOM_WALLET_PREFIX=
      - PHANTOM_ENCRYPTION_PRIVATE_KEY=
      - PHANTOM_ENCRYPTION_PUBLIC_KEY=
      - PHANTOM_SESSION_TTL=
      - PHANTOM_RATE_LIMIT=
      - SHORT_TERM_MEMORY_SIZE=
      - MEDIUM_TERM_MEMORY_EXPIRY=
      - MEMORY_THRESHOLD=
      - OPENAI_API_KEY=
      - MANGO_V3_BASE_URL=
      - MANGO_V3_PRIVATE_KEY_PATH=
    volumes:
      - ./data:/app/data
      - ./keys:/app/keys
    depends_on:
      - redis
    networks:
      - grace-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Redis service
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - grace-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: redis-server --appendonly yes

  # Mango V3 service
  mango-v3-service:
    image: mango/v3:latest  # Use the official Mango V3 image or your custom one
    container_name: mango-v3-service
    ports:
      - "8080:8080"  # Expose the Mango V3 API port
    environment:
      - NODE_ENV=production
      - RPC_URL=
      - NETWORK=
      - PRIVATE_KEY_PATH=/app/keys/mango_private_key.pem
    volumes:
      - ./keys:/app/keys  # Mount the keys directory
      - mango-v3-data:/data  # Persistent storage for Mango V3 data
    networks:
      - grace-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Uncomment and configure these if your Mango V3 service requires additional configuration
    # command: >
    #   --rpc-url 
    #   --network 
    #   --keypair /app/keys/mango_private_key.json

# Networks
networks:
  grace-network:
    driver: bridge

# Volumes
volumes:
  redis-data:
  mango-v3-data:
